spring:
  cloud:
    gateway:
      routes:
        - id: service-a
          uri: http://service-a:8080
          predicates:
            - Path=/a/**

        - id: service-b
          uri: http://service-b:8080
          predicates:
            - Path=/b/**
