spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
            - Path=/a/**

        - id: service-b
          uri: lb://service-b
          predicates:
            - Path=/b/**
